// High-resolution remote cloud assets
export const ASSETS = {
  heroGirl: 'https://starpix-media-production.s3.ap-south-1.amazonaws.com/ai-trends/d0b84582-8bc9-428b-bef6-1ba72f1cc506.jpg',
  heroGirlBefore: 'https://starpix-media-production.s3.ap-south-1.amazonaws.com/ai-trends/530a9c2b-88eb-4cc6-93a1-0e2ce8ea8d30.jpg',
  usageBasic: 'https://starpix-media-production.s3.ap-south-1.amazonaws.com/ai-trends/530a9c2b-88eb-4cc6-93a1-0e2ce8ea8d30.jpg',
  usagePremium: 'https://starpix-media-production.s3.ap-south-1.amazonaws.com/ai-trends/d0b84582-8bc9-428b-bef6-1ba72f1cc506.jpg',
  usageCollage: 'https://starpix-media-production.s3.ap-south-1.amazonaws.com/ai-trends/4c03b402-0f4b-46a6-8241-c3ddc6288dbf.jpg',
  usageVideoStd: 'https://starpix-media-production.s3.ap-south-1.amazonaws.com/ai-trends/c4902ddb-bfbf-4801-91b8-b0e0ba17af7c.jpg',
  usageVideoPrem: 'https://starpix-media-production.s3.ap-south-1.amazonaws.com/subscription/f30784b5-3698-40f5-9f55-4eae4622fcd4.jpg',
};

export const CREDIT_PACKS = [
  {
    id: 'starter',
    nameKey: 'pack_starter',
    descKey: 'pack_starter_desc',
    badgeKey: 'first_purchase_only',
    badgeType: 'starter',
    credits: 25,
    creditsDisplay: '25 AI Credits',
    price: '₹ 25',
    iconType: 'gift',
  },
  {
    id: 'value',
    nameKey: 'pack_value',
    descKey: 'pack_value_desc',
    credits: 50,
    creditsDisplay: '50 AI Credits',
    price: '₹ 49',
    iconType: 'coins_small',
  },
  {
    id: 'creator',
    nameKey: 'pack_creator',
    descKey: 'pack_creator_desc',
    badgeKey: 'most_popular',
    badgeType: 'popular',
    credits: 240,
    creditsDisplay: '240 AI Credits',
    price: '₹ 199',
    iconType: 'coins_med',
    isPopular: true,
  },
  {
    id: 'pro',
    nameKey: 'pack_pro',
    descKey: 'pack_pro_desc',
    credits: 600,
    creditsDisplay: '600 AI Credits',
    price: '₹ 449',
    iconType: 'coins_large',
  },
  {
    id: 'power',
    nameKey: 'pack_power',
    descKey: 'pack_power_desc',
    credits: 1200,
    creditsDisplay: '1,200 AI Credits',
    price: '₹ 799',
    iconType: 'coins_stack',
  },
  {
    id: 'ultimate',
    nameKey: 'pack_ultimate',
    descKey: 'pack_ultimate_desc',
    badgeKey: 'best_value',
    badgeType: 'best_value',
    credits: 2500,
    creditsDisplay: '2,500 AI Credits',
    price: '₹ 1,499',
    iconType: 'coins_gold',
    isBestValue: true,
  },
];

export const USAGE_GUIDE = [
  {
    id: 'basic_image',
    type: 'image',
    titleKey: 'usage_basic_image',
    range: '20–25 Credits',
    image: ASSETS.usageBasic,
  },
  {
    id: 'premium_image',
    type: 'image',
    titleKey: 'usage_premium_image',
    range: '40–60 Credits',
    image: ASSETS.usagePremium,
  },
  {
    id: 'collage',
    type: 'image',
    titleKey: 'usage_collage',
    range: '70–100 Credits',
    image: ASSETS.usageCollage,
  },
  {
    id: 'video_std',
    type: 'video',
    titleKey: 'usage_video_std',
    range: '350–400 Credits',
    image: ASSETS.usageVideoStd,
  },
  {
    id: 'video_prem',
    type: 'video',
    titleKey: 'usage_video_prem',
    range: '450–550 Credits',
    image: ASSETS.usageVideoPrem,
  },
];
