import { StyleSheet } from 'react-native';
import { fontScale, wp, hp } from '../../utils/responsive';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },

  /* Header Bar */
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(0.04),
    paddingBottom: hp(0.01),
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  backBtn: {
    width: wp(0.1),
    height: wp(0.1),
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerCenter: {
    alignItems: 'center',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoStar: {
    marginRight: wp(0.005),
  },
  logoTextStar: {
    fontSize: fontScale(21),
    fontWeight: '900',
    color: '#111827',
    letterSpacing: -0.5,
  },
  logoTextPix: {
    fontSize: fontScale(21),
    fontWeight: '900',
    color: '#EE1D24',
    letterSpacing: -0.5,
  },
  logoSubtitle: {
    fontSize: fontScale(8.5),
    fontWeight: '700',
    color: '#111827',
    letterSpacing: 1.2,
    marginTop: -hp(0.002),
  },
  creditBalancePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEFCE8',
    borderWidth: 1,
    borderColor: '#FEF08A',
    paddingHorizontal: wp(0.028),
    paddingVertical: hp(0.005),
    borderRadius: wp(0.04),
    gap: wp(0.015),
  },
  coinPillIcon: {
    width: wp(0.05),
    height: wp(0.05),
    borderRadius: wp(0.025),
    backgroundColor: '#F59E0B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  coinPillSymbol: {
    color: '#FFFFFF',
    fontSize: fontScale(10),
    fontWeight: '900',
  },
  creditBalanceText: {
    fontSize: fontScale(13),
    fontWeight: '900',
    color: '#111827',
  },

  /* Scroll Content */
  scrollContent: {
    paddingHorizontal: wp(0.04),
    paddingTop: hp(0.015),
  },

  /* Hero Title */
  heroTitleWrap: {
    marginBottom: hp(0.015),
  },
  heroMainTitle: {
    fontSize: fontScale(24),
    fontWeight: '900',
    color: '#EE1D24',
    letterSpacing: -0.5,
  },
  heroSubtitle: {
    fontSize: fontScale(11.5),
    fontWeight: '500',
    color: '#4B5563',
    marginTop: hp(0.002),
  },

  /* Hero Visual Banner */
  heroBanner: {
    flexDirection: 'row',
    backgroundColor: '#FFF1F2',
    borderRadius: wp(0.035),
    borderWidth: 1,
    borderColor: '#FFE4E6',
    padding: wp(0.035),
    marginBottom: hp(0.018),
    overflow: 'hidden',
    position: 'relative',
  },
  heroBannerLeft: {
    flex: 1.15,
    justifyContent: 'center',
  },
  bannerBoldText: {
    fontSize: fontScale(16),
    fontWeight: '900',
    color: '#111827',
  },
  bannerRedText: {
    fontSize: fontScale(16),
    fontWeight: '900',
    color: '#EE1D24',
    marginBottom: hp(0.004),
  },
  bannerDescText: {
    fontSize: fontScale(9.8),
    color: '#6B7280',
    fontWeight: '500',
    lineHeight: fontScale(13.5),
  },
  heroBannerRight: {
    flex: 0.95,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  heroFannedWrap: {
    width: wp(0.28),
    height: wp(0.24),
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fannedCard: {
    position: 'absolute',
    width: wp(0.18),
    height: wp(0.22),
    borderRadius: wp(0.02),
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: wp(0.015),
    elevation: 4,
  },
  fannedCardBack: {
    transform: [{ rotate: '-12deg' }],
    left: wp(0.01),
  },
  fannedCardFront: {
    transform: [{ rotate: '6deg' }],
    right: wp(0.01),
  },
  fannedImg: {
    width: '100%',
    height: '100%',
  },
  playBadgeMini: {
    position: 'absolute',
    bottom: -hp(0.005),
    right: -wp(0.01),
    width: wp(0.06),
    height: wp(0.06),
    borderRadius: wp(0.03),
    backgroundColor: '#EE1D24',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  magicScriptWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(0.006),
  },
  magicScriptText: {
    fontSize: fontScale(9.5),
    fontWeight: '700',
    color: '#EE1D24',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  magicStar: {
    marginLeft: 2,
  },

  /* Packs Container */
  packsContainer: {
    gap: hp(0.01),
    marginBottom: hp(0.02),
  },
  packCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: wp(0.035),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: wp(0.03),
    paddingVertical: hp(0.012),
  },
  packCardSelected: {
    borderColor: '#FDA4AF',
    borderWidth: 1.6,
    backgroundColor: '#FFFDFD',
    shadowColor: '#EE1D24',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: wp(0.02),
    elevation: 3,
  },
  packCardBestValue: {
    borderColor: '#FDE047',
    backgroundColor: '#FEFCE8',
  },

  /* Left Coin Graphics */
  packLeftCol: {
    width: wp(0.14),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp(0.02),
  },
  coinStackWrap: {
    width: wp(0.12),
    height: wp(0.11),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  coinCircleB: {
    width: wp(0.095),
    height: wp(0.095),
    borderRadius: wp(0.0475),
    backgroundColor: '#F59E0B',
    borderWidth: 2,
    borderColor: '#FDE68A',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#B45309',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  coinCircleS: {
    width: wp(0.095),
    height: wp(0.095),
    borderRadius: wp(0.0475),
    backgroundColor: '#F59E0B',
    borderWidth: 2,
    borderColor: '#FDE68A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  coinSymbolText: {
    color: '#FFFFFF',
    fontSize: fontScale(12),
    fontWeight: '900',
  },
  coinLayerBack: {
    position: 'absolute',
    top: 2,
    left: 4,
    width: wp(0.09),
    height: wp(0.09),
    borderRadius: wp(0.045),
    backgroundColor: '#D97706',
  },
  coinLayerMid: {
    position: 'absolute',
    top: 5,
    left: 7,
    width: wp(0.09),
    height: wp(0.09),
    borderRadius: wp(0.045),
    backgroundColor: '#FBBF24',
  },
  giftBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
  },
  giftEmoji: {
    fontSize: fontScale(13),
  },

  /* Center Details */
  packMidCol: {
    flex: 1,
    justifyContent: 'center',
  },
  packTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: wp(0.015),
  },
  packName: {
    fontSize: fontScale(13.5),
    fontWeight: '800',
    color: '#111827',
  },
  starterName: {
    color: '#EE1D24',
  },
  packBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(0.018),
    paddingVertical: hp(0.0025),
    borderRadius: wp(0.02),
  },
  starterBadge: {
    backgroundColor: '#EE1D24',
  },
  popularBadge: {
    backgroundColor: '#EE1D24',
  },
  bestValueBadge: {
    backgroundColor: '#EE1D24',
  },
  badgeCrownEmoji: {
    fontSize: fontScale(8.5),
    marginRight: 2,
  },
  packBadgeText: {
    color: '#FFFFFF',
    fontSize: fontScale(8),
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  packCreditsText: {
    fontSize: fontScale(13),
    fontWeight: '900',
    color: '#111827',
    marginTop: hp(0.002),
  },
  packDescText: {
    fontSize: fontScale(10),
    color: '#6B7280',
    fontWeight: '500',
    marginTop: hp(0.001),
  },
  creatorDescText: {
    color: '#2563EB',
    fontWeight: '600',
  },

  /* Right Price Box */
  priceBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: wp(0.025),
    paddingHorizontal: wp(0.028),
    paddingVertical: hp(0.008),
    gap: wp(0.01),
  },
  priceBoxSelected: {
    borderColor: '#FDA4AF',
    backgroundColor: '#FFF5F5',
  },
  priceText: {
    fontSize: fontScale(14),
    fontWeight: '800',
    color: '#111827',
  },

  /* How AI Credits Are Used Guide Section */
  guideSection: {
    backgroundColor: '#FFFBFB',
    borderRadius: wp(0.035),
    borderWidth: 1,
    borderColor: '#FEE2E2',
    padding: wp(0.03),
    marginTop: hp(0.005),
  },
  guideHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(0.01),
  },
  guideHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.015),
  },
  bulbCircle: {
    width: wp(0.06),
    height: wp(0.06),
    borderRadius: wp(0.03),
    backgroundColor: '#EE1D24',
    justifyContent: 'center',
    alignItems: 'center',
  },
  guideTitle: {
    fontSize: fontScale(12.5),
    fontWeight: '900',
    color: '#EE1D24',
  },
  guideCardsRow: {
    gap: wp(0.02),
    paddingTop: hp(0.005),
  },
  guideItemCard: {
    width: wp(0.24),
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: wp(0.02),
    borderWidth: 1,
    borderColor: '#F3F4F6',
    padding: wp(0.015),
  },
  guideItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    height: hp(0.035),
  },
  guideItemType: {
    fontSize: fontScale(8.2),
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
    lineHeight: fontScale(10.5),
  },
  guideCreditsBadge: {
    backgroundColor: '#FFE4E6',
    paddingHorizontal: wp(0.015),
    paddingVertical: hp(0.002),
    borderRadius: wp(0.01),
    marginVertical: hp(0.004),
  },
  guideCreditsText: {
    fontSize: fontScale(8),
    fontWeight: '800',
    color: '#EE1D24',
  },
  guideThumbWrap: {
    width: wp(0.2),
    height: wp(0.2),
    borderRadius: wp(0.015),
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F3F4F6',
  },
  guideThumbImg: {
    width: '100%',
    height: '100%',
  },
  guidePlayOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  /* Floating Bottom Bar */
  bottomFixedBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    paddingHorizontal: wp(0.04),
    paddingTop: hp(0.012),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: wp(0.02),
    elevation: 8,
  },
  continueButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EE1D24',
    borderRadius: wp(0.06),
    paddingVertical: hp(0.016),
    shadowColor: '#EE1D24',
    shadowOffset: { width: 0, height: hp(0.004) },
    shadowOpacity: 0.35,
    shadowRadius: wp(0.02),
    elevation: 4,
  },
  continueButtonText: {
    fontSize: fontScale(16),
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  trustBadgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp(0.008),
    paddingHorizontal: wp(0.02),
  },
  trustBadgeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.01),
  },
  trustDivider: {
    width: 1,
    height: hp(0.016),
    backgroundColor: '#E5E7EB',
  },
  trustBadgeText: {
    fontSize: fontScale(9.5),
    fontWeight: '500',
    color: '#4B5563',
  },
});
