import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONTS } from '../../constants/colors';
import { fontScale, wp, hp, SCREEN_PAD } from '../../utils/responsive';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SCREEN_PAD,
    paddingBottom: hp(0.012),
    backgroundColor: '#FFFFFF',
  },
  userGreetingWrap: {
    justifyContent: 'center',
  },
  welcomeText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.medium,
    color: '#6B7280',
    marginBottom: 1,
  },
  userNameText: {
    fontSize: fontScale(21),
    fontFamily: FONTS.bold,
    color: '#111827',
    letterSpacing: -0.3,
  },
  headerActionsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.02),
  },
  aiTrendsBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#FDA4AF',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  aiTrendsContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  aiTrendsText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#E11D48',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  langBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconCenter: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  langIconText: {
    fontSize: fontScale(15),
    fontFamily: FONTS.bold,
    color: '#E11D48',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  proBtn: {
    backgroundColor: '#1E1B2E',
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: '#F59E0B',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  proContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  crownIcon: {
    fontSize: fontScale(12),
  },
  proText: {
    fontSize: fontScale(11.5),
    fontFamily: FONTS.black,
    color: '#FBBF24',
    letterSpacing: 0.5,
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(15),
  },
  optionsBtn: {
    width: 28,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    alignItems: 'center',
  },
  categoryContainer: {
    width: '100%',
    paddingHorizontal: SCREEN_PAD,
    marginVertical: hp(0.008),
    gap: hp(0.008),
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.018),
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 20,
    paddingHorizontal: wp(0.026),
    paddingVertical: hp(0.007),
    gap: 4,
  },
  chipActive: {
    backgroundColor: '#9F1239',
    borderColor: '#9F1239',
  },
  chipSpecialInactive: {
    borderColor: '#FECDD3',
  },
  chipIcon: {
    fontSize: fontScale(11.5),
  },
  chipText: {
    fontSize: fontScale(11.5),
    fontFamily: FONTS.medium,
    color: '#1F2937',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  chipTextActive: {
    color: '#FFFFFF',
    fontFamily: FONTS.bold,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  reelCard: {
    borderRadius: wp(0.045),
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#1C1917',
    marginTop: hp(0.006),
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 8,
  },
  playPauseBtn: {
    position: 'absolute',
    right: wp(0.035),
    top: '48%',
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    zIndex: 30,
  },
  nextPillBtn: {
    position: 'absolute',
    right: wp(0.035),
    bottom: hp(0.02),
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    zIndex: 30,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  nextPillContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  nextPillText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#111827',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(0.02),
    marginTop: hp(0.012),
  },
  downloadActionBtn: {
    flex: 1.1,
    height: hp(0.048),
    backgroundColor: '#EF4444',
    borderRadius: 24,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  shareActionBtn: {
    flex: 1.1,
    height: hp(0.048),
    backgroundColor: '#22C55E',
    borderRadius: 24,
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  editActionBtn: {
    flex: 1.0,
    height: hp(0.048),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#FDA4AF',
    borderRadius: 24,
  },
  actionBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    paddingHorizontal: 6,
    gap: 5,
  },
  downloadActionText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#FFFFFF',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  shareActionText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#FFFFFF',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  editActionText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#E11D48',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  frameSelectorWrap: {
    marginTop: hp(0.012),
  },
  frameScrollContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.02),
  },
  frameBox: {
    width: wp(0.125),
    height: wp(0.125),
    borderRadius: wp(0.025),
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  frameBoxNone: {
    backgroundColor: '#FFF1F2',
    borderColor: '#FECDD3',
  },
  frameBoxActive: {
    borderColor: '#E11D48',
    borderWidth: 2.2,
  },
  frameThumbImage: {
    width: '100%',
    height: '100%',
  },
  scrollIndicatorWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp(0.014),
  },
  scrollIndicatorText: {
    fontSize: fontScale(11),
    fontFamily: FONTS.medium,
    color: '#8E8E93',
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 36,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: fontScale(16),
    fontFamily: FONTS.bold,
    color: '#111827',
  },
  langOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 12,
  },
  langOptionItemActive: {
    backgroundColor: '#FFF1F2',
    marginHorizontal: -8,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  langFlag: {
    fontSize: fontScale(20),
  },
  langName: {
    fontSize: fontScale(14),
    fontFamily: FONTS.medium,
    color: '#1F2937',
  },
  langNameActive: {
    fontFamily: FONTS.bold,
    color: '#E11D48',
  },
  langNative: {
    fontSize: fontScale(12),
    fontFamily: FONTS.regular,
    color: '#6B7280',
  },
  optionsSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 36,
    gap: 6,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  menuItemText: {
    fontSize: fontScale(14.5),
    fontFamily: FONTS.medium,
    color: '#1F2937',
  },
});
