import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS, FONTS } from '../../constants/colors';
import { fontScale, wp, hp, SCREEN_PAD } from '../../utils/responsive';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SCREEN_PAD,
    paddingBottom: hp(0.012),
    backgroundColor: '#FFFFFF',
  },
  userGreetingWrap: {
    flex: 1,
    minWidth: 0,
    marginRight: 8,
    justifyContent: 'center',
  },
  welcomeText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.medium,
    color: '#6B7280',
    marginBottom: 1,
  },
  userNameText: {
    fontSize: fontScale(20),
    fontFamily: FONTS.bold,
    color: '#111827',
    letterSpacing: -0.3,
  },
  headerActionsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    gap: wp(0.018),
  },
  aiTrendsBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#FDA4AF',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  aiTrendsContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  aiTrendsText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#E11D48',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  langBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconCenter: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  langIconText: {
    fontSize: fontScale(15),
    fontFamily: FONTS.bold,
    color: '#E11D48',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  proBtn: {
    backgroundColor: '#F59E0B',
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: '#D97706',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  proContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  crownIcon: {
    fontSize: fontScale(12),
  },
  proText: {
    fontSize: fontScale(11.5),
    fontFamily: FONTS.black,
    color: '#1E1B2E',
    letterSpacing: 0.5,
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(15),
  },
  scrollContent: {
    alignItems: 'center',
  },
  pageContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    paddingVertical: 2,
  },
  categoryContainer: {
    width: '100%',
    paddingHorizontal: wp(0.025),
    paddingTop: 3,
    paddingBottom: 5,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    zIndex: 20,
    gap: 4,
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.014),
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 3,
  },
  chipActive: {
    backgroundColor: '#9F1239',
    borderColor: '#9F1239',
  },
  chipSpecialInactive: {
    borderColor: '#FECDD3',
  },
  chipIcon: {
    fontSize: fontScale(11.5),
  },
  chipText: {
    fontSize: fontScale(11.5),
    fontFamily: FONTS.medium,
    color: '#1F2937',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  chipTextActive: {
    color: '#FFFFFF',
    fontFamily: FONTS.bold,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  cardRowWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  reelCard: {
    borderRadius: wp(0.045),
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#1C1917',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 8,
  },
  paidReelBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EA580C',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 7,
    gap: 4,
    zIndex: 35,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
  },
  paidBadgeCrownWrap: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Platform.OS === 'android' ? 1.5 : 0.8,
  },
  paidReelBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: fontScale(10.5),
    color: '#FFFFFF',
    letterSpacing: 0.3,
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(14),
  },
  playPauseBtn: {
    position: 'absolute',
    right: wp(0.035),
    top: '48%',
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    zIndex: 30,
  },
  floatingNextBtn: {
    position: 'absolute',
    right: 8,
    bottom: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#FDA4AF',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    zIndex: 40,
    shadowColor: '#E11D48',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  nextPillBtn: {
    position: 'absolute',
    right: 8,
    bottom: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#FDA4AF',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    zIndex: 40,
    shadowColor: '#E11D48',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  nextPillContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  nextPillText: {
    fontSize: fontScale(11.5),
    fontFamily: FONTS.bold,
    color: '#E11D48',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(15),
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(0.02),
    marginTop: 6,
  },
  downloadActionBtn: {
    flex: 1.1,
    height: 38,
    backgroundColor: '#EF4444',
    borderRadius: 20,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  shareActionBtn: {
    flex: 1.1,
    height: 38,
    backgroundColor: '#22C55E',
    borderRadius: 20,
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  editActionBtn: {
    flex: 1.0,
    height: 38,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#FDA4AF',
    borderRadius: 20,
  },
  actionBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    paddingHorizontal: 6,
    gap: 5,
  },
  downloadActionText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#FFFFFF',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  shareActionText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#FFFFFF',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  editActionText: {
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    color: '#E11D48',
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(16),
  },
  frameSelectorWrap: {
    marginTop: 6,
  },
  frameScrollContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.02),
  },
  frameBox: {
    width: 44,
    height: 44,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  frameBoxNone: {
    backgroundColor: '#FFF1F2',
    borderColor: '#FECDD3',
  },
  frameBoxActive: {
    borderColor: '#E11D48',
    borderWidth: 2.2,
  },
  frameBoxContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  frameThumbImage: {
    width: '100%',
    height: '100%',
  },
  scrollIndicatorWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    paddingBottom: 2,
  },
  scrollIndicatorText: {
    fontSize: fontScale(11),
    fontFamily: FONTS.medium,
    color: '#8E8E93',
    marginTop: 2,
  },
  scrollIndicatorSpacer: {
    height: 24,
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 36,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: fontScale(16),
    fontFamily: FONTS.bold,
    color: '#111827',
  },
  langOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 12,
  },
  langOptionItemActive: {
    backgroundColor: '#FFF1F2',
    marginHorizontal: -8,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  langFlag: {
    fontSize: fontScale(20),
  },
  langName: {
    fontSize: fontScale(14),
    fontFamily: FONTS.medium,
    color: '#1F2937',
  },
  langNameActive: {
    fontFamily: FONTS.bold,
    color: '#E11D48',
  },
  langNative: {
    fontSize: fontScale(12),
    fontFamily: FONTS.regular,
    color: '#6B7280',
  },
  floatingLoaderBadge: {
    position: 'absolute',
    top: hp(0.12),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(17, 24, 39, 0.92)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    gap: 8,
    zIndex: 100,
    elevation: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  floatingLoaderText: {
    color: '#FFFFFF',
    fontSize: fontScale(13),
    fontFamily: FONTS.semiBold,
  },
});
