import { StyleSheet } from 'react-native';
import { fontScale, wp, hp } from '../../utils/responsive';
import { FONTS } from '../../constants/colors';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },

  /* Header Bar */
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(0.04),
    paddingBottom: hp(0.01),
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  backBtn: {
    width: wp(0.09),
    height: wp(0.09),
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  titleWrap: {
    marginLeft: wp(0.01),
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleStar: {
    marginRight: wp(0.01),
  },
  titleText: {
    fontSize: fontScale(19),
    fontWeight: '900',
    color: '#111827',
    letterSpacing: -0.4,
  },
  subtitleText: {
    fontSize: fontScale(9.8),
    color: '#9CA3AF',
    fontWeight: '500',
    marginTop: -hp(0.002),
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(0.025),
  },
  langBtn: {
    width: wp(0.08),
    height: wp(0.08),
    justifyContent: 'center',
    alignItems: 'center',
  },
  langIconText: {
    fontSize: fontScale(15),
    fontWeight: '700',
    color: '#EE1D24',
  },
  headerCreditsPill: {
    borderRadius: wp(0.04),
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  headerCreditsContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FCD34D',
    paddingHorizontal: wp(0.024),
    paddingVertical: hp(0.005),
    borderRadius: wp(0.04),
    gap: wp(0.012),
  },
  headerCreditsIconBox: {
    width: wp(0.046),
    height: wp(0.046),
    borderRadius: wp(0.023),
    backgroundColor: '#F59E0B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerCreditsValue: {
    fontSize: fontScale(12),
    fontWeight: '800',
    color: '#92400E',
  },
  proBtn: {
    backgroundColor: '#F59E0B',
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: '#D97706',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  proContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  proText: {
    fontSize: fontScale(11.5),
    fontFamily: FONTS.black,
    color: '#1E1B2E',
    letterSpacing: 0.5,
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(15),
  },

  /* Scroll Content */
  scrollContent: {
    paddingHorizontal: wp(0.04),
    paddingTop: hp(0.01),
  },

  /* Quick Action Bar */
  quickActionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: wp(0.03),
    marginVertical: hp(0.01),
  },
  buyCreditsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEFCE8',
    borderWidth: 1,
    borderColor: '#FEF08A',
    paddingHorizontal: wp(0.035),
    paddingVertical: hp(0.008),
    borderRadius: wp(0.05),
    gap: wp(0.015),
  },
  coinBadge: {
    width: wp(0.045),
    height: wp(0.045),
    borderRadius: wp(0.0225),
    backgroundColor: '#F59E0B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  coinText: {
    color: '#FFFFFF',
    fontSize: fontScale(9.5),
    fontWeight: '900',
  },
  buyCreditsText: {
    fontSize: fontScale(11.5),
    fontWeight: '700',
    color: '#D97706',
  },
  historyPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EE1D24',
    paddingHorizontal: wp(0.04),
    paddingVertical: hp(0.008),
    borderRadius: wp(0.05),
    gap: wp(0.015),
  },
  historyText: {
    fontSize: fontScale(11.5),
    fontWeight: '700',
    color: '#FFFFFF',
  },

  /* Categories Chips */
  categoriesScroll: {
    paddingVertical: hp(0.006),
    gap: wp(0.018),
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: wp(0.03),
    paddingVertical: hp(0.007),
    borderRadius: wp(0.05),
  },
  categoryChipSelected: {
    backgroundColor: '#EE1D24',
    borderColor: '#EE1D24',
  },
  catIcon: {
    marginRight: wp(0.012),
  },
  categoryText: {
    fontSize: fontScale(11),
    fontWeight: '600',
    color: '#374151',
  },
  categoryTextSelected: {
    color: '#FFFFFF',
  },

  /* Hero Featured Template Viewer */
  heroCard: {
    marginTop: hp(0.012),
    backgroundColor: '#FFFFFF',
    borderRadius: wp(0.04),
    borderWidth: 1,
    borderColor: '#F3F4F6',
    padding: wp(0.03),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: wp(0.02),
    elevation: 3,
  },

  /* Before Row */
  beforeRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: wp(0.03),
    marginBottom: hp(0.012),
    position: 'relative',
    overflow: 'visible',
    zIndex: 25,
  },
  beforeContainer: {
    flex: 1.15,
    backgroundColor: '#F9FAFB',
    borderRadius: wp(0.03),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: wp(0.02),
    position: 'relative',
    minHeight: hp(0.13),
    overflow: 'visible',
  },
  beforeBadge: {
    position: 'absolute',
    top: hp(0.006),
    left: wp(0.018),
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: wp(0.018),
    paddingVertical: hp(0.002),
    borderRadius: wp(0.015),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    zIndex: 5,
  },
  beforeBadgeText: {
    fontSize: fontScale(8.5),
    fontWeight: '700',
    color: '#111827',
  },
  beforePhotosRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: wp(0.02),
    marginTop: hp(0.018),
  },
  beforePhotoWrap: {
    width: wp(0.18),
    height: wp(0.18),
    borderRadius: wp(0.02),
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#E5E7EB',
  },
  beforePhotoImg: {
    width: '100%',
    height: '100%',
  },
  emptyBeforePhoto: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeFaceBtn: {
    position: 'absolute',
    top: 3,
    right: 3,
    width: wp(0.045),
    height: wp(0.045),
    borderRadius: wp(0.0225),
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
  },
  slotTag: {
    position: 'absolute',
    bottom: 2,
    left: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    zIndex: 4,
  },
  slotTagText: {
    fontSize: fontScale(7.5),
    fontWeight: '700',
    color: '#FFFFFF',
  },
  slotDoneBadge: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: '#16A34A',
    width: wp(0.045),
    height: wp(0.045),
    borderRadius: wp(0.0225),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    zIndex: 4,
  },

  /* Upload Card */
  uploadCard: {
    flex: 1,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#EE1D24',
    borderRadius: wp(0.03),
    backgroundColor: '#FFF5F5',
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(0.025),
    position: 'relative',
    overflow: 'visible',
  },
  uploadIconBadge: {
    marginBottom: hp(0.004),
  },
  uploadTitle: {
    fontSize: fontScale(11.5),
    fontWeight: '800',
    color: '#111827',
    textAlign: 'center',
  },
  uploadSubtitle: {
    fontSize: fontScale(9.5),
    color: '#6B7280',
    marginTop: hp(0.002),
    textAlign: 'center',
  },
  uploadCardActive: {
    borderColor: '#16A34A',
    backgroundColor: '#F0FDF4',
  },
  uploadCardHalfActive: {
    borderColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
  },
  uploadIconBadgeActive: {
    backgroundColor: '#DCFCE7',
    borderRadius: 20,
    padding: 2,
  },
  uploadIconBadgeHalfActive: {
    backgroundColor: '#FEF3C7',
    borderRadius: 20,
    padding: 2,
  },
  addFaceBadge: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: '#EE1D24',
    borderRadius: wp(0.025),
    width: wp(0.05),
    height: wp(0.05),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },

  /* Curved Transformation Arrow Connector from Before Box to After */
  arrowConnectorWrap: {
    position: 'absolute',
    bottom: -16,
    right: 8,
    zIndex: 99,
    elevation: 10,
  },
  beforeAfterConnector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: hp(0.008),
    zIndex: 15,
  },
  connectorLine: {
    flex: 1,
    height: 1.5,
    backgroundColor: '#F3F4F6',
  },
  connectorBadge: {
    width: wp(0.075),
    height: wp(0.075),
    borderRadius: wp(0.0375),
    backgroundColor: '#EE1D24',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: wp(0.025),
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#EE1D24',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 4,
  },

  /* After Card */
  afterCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(0.03),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
    padding: wp(0.025),
  },
  afterTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(0.008),
  },
  afterBadge: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: wp(0.02),
    paddingVertical: hp(0.003),
    borderRadius: wp(0.015),
  },
  afterBadgeText: {
    fontSize: fontScale(9.5),
    fontWeight: '700',
    color: '#111827',
  },
  mediaTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFE4E6',
    paddingHorizontal: wp(0.02),
    paddingVertical: hp(0.003),
    borderRadius: wp(0.015),
  },
  mediaTypeBadgeText: {
    fontSize: fontScale(9.5),
    fontWeight: '700',
    color: '#EE1D24',
  },

  /* Main Media */
  mediaContainer: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: wp(0.025),
    overflow: 'hidden',
    backgroundColor: '#000000',
    position: 'relative',
  },
  mediaPreviewWrap: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  mainMedia: {
    width: '100%',
    height: '100%',
  },
  playButtonOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 40,
  },
  playButtonCircle: {
    width: wp(0.13),
    height: wp(0.13),
    borderRadius: wp(0.065),
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 6,
  },
  playButtonCirclePlaying: {
    backgroundColor: 'rgba(0, 0, 0, 0.38)',
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  durationBadge: {
    position: 'absolute',
    bottom: hp(0.01),
    right: wp(0.02),
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    paddingHorizontal: wp(0.018),
    paddingVertical: hp(0.002),
    borderRadius: wp(0.01),
    zIndex: 10,
  },
  durationText: {
    fontSize: fontScale(9),
    color: '#FFFFFF',
    fontWeight: '700',
  },
  soundBadgeContainer: {
    position: 'absolute',
    top: hp(0.015),
    right: wp(0.03),
    zIndex: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(0.028),
    paddingVertical: hp(0.007),
    borderRadius: wp(0.04),
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    gap: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 6,
  },
  soundBadgeText: {
    color: '#FFFFFF',
    fontSize: fontScale(11),
    fontFamily: FONTS.bold,
    letterSpacing: 0.2,
    includeFontPadding: false,
  },
  catEmoji: {
    fontSize: fontScale(13),
    marginRight: 4,
  },
  /* Premium Loading Overlay for Generation & Media Buffering */
  loadingBlurredBackdrop: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  loadingDimmerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 12, 24, 0.84)',
  },
  loadingOverlayContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
    elevation: 12,
    paddingHorizontal: wp(0.06),
  },
  loadingTopBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.45)',
    paddingHorizontal: wp(0.03),
    paddingVertical: hp(0.005),
    borderRadius: wp(0.03),
    marginBottom: hp(0.016),
    gap: wp(0.012),
  },
  loadingTopBadgeText: {
    fontSize: fontScale(10),
    fontWeight: '800',
    color: '#F59E0B',
    letterSpacing: 0.8,
  },
  loadingPulseOuterRing: {
    width: wp(0.20),
    height: wp(0.20),
    borderRadius: wp(0.10),
    backgroundColor: 'rgba(238, 29, 36, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(238, 29, 36, 0.35)',
  },
  loadingPulseInnerBadge: {
    width: wp(0.14),
    height: wp(0.14),
    borderRadius: wp(0.07),
    backgroundColor: '#EE1D24',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#EE1D24',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 8,
    elevation: 6,
  },
  loadingSpinner: {
    marginTop: hp(0.014),
  },
  loadingPrimaryTitle: {
    fontSize: fontScale(14),
    fontWeight: '800',
    color: '#FFFFFF',
    marginTop: hp(0.012),
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  loadingSecondarySubtitle: {
    fontSize: fontScale(10.5),
    fontWeight: '500',
    color: '#D1D5DB',
    marginTop: hp(0.005),
    textAlign: 'center',
    lineHeight: fontScale(15),
  },
  loadingProgressTrack: {
    width: wp(0.55),
    height: hp(0.006),
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    borderRadius: hp(0.003),
    overflow: 'hidden',
    marginTop: hp(0.018),
  },
  loadingProgressFill: {
    height: '100%',
    backgroundColor: '#F59E0B',
    borderRadius: hp(0.003),
  },
  generatingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
    elevation: 10,
    paddingHorizontal: wp(0.06),
  },
  resultLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 99,
    elevation: 8,
  },
  resultActionBtnDisabled: {
    opacity: 0.5,
  },
  createButtonDisabled: {
    opacity: 0.8,
  },

  /* Card Info Row */
  cardInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp(0.01),
  },
  templateTitle: {
    fontSize: fontScale(14),
    fontWeight: '900',
    color: '#111827',
    flex: 1,
    letterSpacing: -0.3,
  },
  templateDetailsRight: {
    alignItems: 'flex-end',
  },
  uploadCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  uploadCountText: {
    fontSize: fontScale(10.5),
    fontWeight: '700',
    color: '#EE1D24',
  },
  creditText: {
    fontSize: fontScale(10),
    fontWeight: '600',
    color: '#D97706',
    marginTop: hp(0.002),
  },

  /* Big Red CTA Button */
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EE1D24',
    borderRadius: wp(0.06),
    paddingVertical: hp(0.016),
    marginTop: hp(0.014),
    shadowColor: '#EE1D24',
    shadowOffset: { width: 0, height: hp(0.004) },
    shadowOpacity: 0.35,
    shadowRadius: wp(0.02),
    elevation: 4,
  },
  createButtonText: {
    fontSize: fontScale(14),
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },

  /* Result Action Buttons (Download, Share, Re-create) */
  resultActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(0.018),
    marginTop: hp(0.014),
  },
  resultActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(0.013),
    paddingHorizontal: wp(0.014),
    borderRadius: wp(0.06),
    gap: wp(0.012),
  },
  downloadBtn: {
    backgroundColor: '#EE1D24',
    shadowColor: '#EE1D24',
    shadowOffset: { width: 0, height: hp(0.004) },
    shadowOpacity: 0.35,
    shadowRadius: wp(0.02),
    elevation: 4,
  },
  shareBtn: {
    backgroundColor: '#1E1B2E',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: hp(0.003) },
    shadowOpacity: 0.2,
    shadowRadius: wp(0.02),
    elevation: 3,
  },
  createAgainBtn: {
    backgroundColor: '#FFF1F2',
    borderWidth: 1.2,
    borderColor: '#FDA4AF',
  },
  resultActionBtnText: {
    fontSize: fontScale(11.5),
    fontWeight: '700',
    color: '#FFFFFF',
  },
  createAgainBtnText: {
    fontSize: fontScale(11.5),
    fontWeight: '700',
    color: '#EE1D24',
  },

  /* Feed Section */
  feedSection: {
    marginTop: hp(0.015),
    gap: hp(0.012),
  },
  feedCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: wp(0.03),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: wp(0.025),
    alignItems: 'center',
    gap: wp(0.03),
  },
  feedThumbWrap: {
    width: wp(0.24),
    height: wp(0.24),
    borderRadius: wp(0.025),
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F3F4F6',
  },
  feedThumbImg: {
    width: '100%',
    height: '100%',
  },
  feedPlayIcon: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  feedDetails: {
    flex: 1,
    justifyContent: 'space-between',
    height: wp(0.24),
    paddingVertical: hp(0.002),
  },
  feedTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  feedTitleText: {
    fontSize: fontScale(12.5),
    fontWeight: '800',
    color: '#111827',
    flex: 1,
    marginRight: wp(0.01),
  },
  feedMediaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFE4E6',
    paddingHorizontal: wp(0.015),
    paddingVertical: hp(0.002),
    borderRadius: wp(0.01),
  },
  feedMediaBadgeText: {
    fontSize: fontScale(8.5),
    fontWeight: '700',
    color: '#EE1D24',
  },
  feedCreditText: {
    fontSize: fontScale(10),
    fontWeight: '600',
    color: '#D97706',
  },
  feedMiniButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF1F2',
    borderWidth: 1,
    borderColor: '#FECDD3',
    borderRadius: wp(0.04),
    paddingVertical: hp(0.008),
    paddingHorizontal: wp(0.03),
    alignSelf: 'flex-start',
  },
  feedMiniButtonText: {
    fontSize: fontScale(11),
    fontWeight: '700',
    color: '#EE1D24',
  },

  /* Language Modal */
  langModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(0.05),
  },
  langModalCard: {
    width: '100%',
    maxHeight: hp(0.7),
    backgroundColor: '#FFFFFF',
    borderRadius: wp(0.04),
    padding: wp(0.04),
  },
  langModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(0.015),
    paddingBottom: hp(0.01),
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  langModalTitle: {
    fontSize: fontScale(15),
    fontWeight: '800',
    color: '#111827',
  },
  langItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp(0.012),
    borderBottomWidth: 1,
    borderBottomColor: '#F9FAFB',
  },
  langItemSelected: {
    backgroundColor: '#FEF2F2',
    borderRadius: wp(0.02),
    paddingHorizontal: wp(0.02),
  },
  langText: {
    fontSize: fontScale(13),
    color: '#374151',
    fontWeight: '500',
  },
  langTextSelected: {
    color: '#EE1D24',
    fontWeight: '700',
  },
});
