import { StyleSheet } from 'react-native';
import { BRUTAL, FONTS, COLORS } from '../../constants/colors';
import { fontScale, wp, hp } from '../../utils/responsive';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(23, 18, 12, 0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(0.04),
  },
  sheet: {
    width: '100%',
    maxWidth: 480,
  },
  sheetFace: {
    backgroundColor: BRUTAL.bone,
    maxHeight: hp(0.88),
  },
  scroll: {
    flexShrink: 1,
  },
  toolbar: {
    backgroundColor: BRUTAL.ink,
    paddingHorizontal: wp(0.045),
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
    overflow: 'hidden',
  },
  flameCorner: {
    position: 'absolute',
    right: -24,
    top: -24,
    width: 56,
    height: 56,
    backgroundColor: BRUTAL.flame,
  },
  toolbarTitle: {
    color: BRUTAL.paper,
    fontSize: fontScale(16),
    fontFamily: FONTS.display,
    letterSpacing: 0.5,
  },
  closeBtn: {
    width: 34,
    height: 34,
    backgroundColor: BRUTAL.flame,
    borderWidth: 2,
    borderColor: BRUTAL.paper,
    zIndex: 1,
  },
  closeContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    padding: wp(0.045),
    paddingBottom: wp(0.06),
  },
  masthead: {
    backgroundColor: BRUTAL.ink,
    borderWidth: 2,
    borderColor: BRUTAL.ink,
    paddingHorizontal: wp(0.04),
    paddingVertical: hp(0.022),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  brandBadge: {
    width: 40,
    height: 40,
    backgroundColor: BRUTAL.flame,
    borderWidth: 2,
    borderColor: BRUTAL.paper,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  brandBadgeLetter: {
    color: BRUTAL.ink,
    fontSize: fontScale(20),
    fontFamily: FONTS.display,
  },
  brandName: {
    color: BRUTAL.paper,
    fontSize: fontScale(18),
    fontFamily: FONTS.display,
    letterSpacing: 0.5,
  },
  brandSub: {
    color: BRUTAL.flameLight,
    fontSize: fontScale(7.5),
    fontFamily: FONTS.bold,
    letterSpacing: 1.6,
    marginTop: 2,
  },
  invoiceTag: {
    alignItems: 'flex-end',
  },
  invoiceTagText: {
    color: BRUTAL.paper,
    fontSize: fontScale(22),
    fontFamily: FONTS.display,
    letterSpacing: 0.5,
  },
  invoiceTagSub: {
    color: 'rgba(245, 241, 232, 0.6)',
    fontSize: fontScale(7),
    fontFamily: FONTS.bold,
    letterSpacing: 1.5,
    marginTop: 1,
  },
  metaGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
    marginTop: hp(0.024),
  },
  billedCol: {
    flex: 1,
  },
  uidBox: {
    backgroundColor: BRUTAL.paperAlt,
    borderWidth: 1.5,
    borderColor: BRUTAL.ink,
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  uidLabel: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(8.5),
    fontFamily: FONTS.bold,
    letterSpacing: 1,
  },
  uidValue: {
    color: BRUTAL.ink,
    fontSize: fontScale(10.5),
    fontFamily: FONTS.bold,
    letterSpacing: 0.5,
    flexShrink: 1,
    marginLeft: 8,
  },
  sectionLabel: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(8.5),
    fontFamily: FONTS.bold,
    letterSpacing: 1.4,
    marginBottom: 4,
  },
  metaTitle: {
    color: BRUTAL.ink,
    fontSize: fontScale(13),
    fontFamily: FONTS.bold,
  },
  metaSmall: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(10),
    fontFamily: FONTS.medium,
    marginTop: 2,
  },
  metaSmallMono: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(9.5),
    fontFamily: FONTS.semibold,
    marginTop: 2,
  },
  invoiceMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: hp(0.022),
    paddingTop: hp(0.018),
    borderTopWidth: 2,
    borderTopColor: 'rgba(23, 18, 12, 0.15)',
  },
  metaRow: {
    flex: 1,
    minWidth: '40%',
  },
  metaLabel: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(8.5),
    fontFamily: FONTS.bold,
    letterSpacing: 1.2,
    marginBottom: 3,
  },
  metaValue: {
    color: BRUTAL.inkSoft,
    fontSize: fontScale(10.5),
    fontFamily: FONTS.semibold,
  },
  metaValueStrong: {
    color: BRUTAL.ink,
    fontFamily: FONTS.bold,
  },
  metaValueMono: {
    color: BRUTAL.inkSoft,
    fontSize: fontScale(9.5),
    fontFamily: FONTS.semibold,
  },
  statusStamp: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 4,
    borderWidth: 1.5,
    borderRadius: 2,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  statusStampText: {
    fontSize: fontScale(8.5),
    fontFamily: FONTS.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: BRUTAL.paperAlt,
    borderWidth: 2,
    borderColor: BRUTAL.ink,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginTop: hp(0.016),
  },
  tableHeaderCell: {
    color: BRUTAL.ink,
    fontSize: fontScale(8.5),
    fontFamily: FONTS.bold,
    letterSpacing: 1,
  },
  cellDesc: {
    flex: 1,
  },
  cellQty: {
    width: 44,
    textAlign: 'center',
  },
  cellAmt: {
    width: 86,
    textAlign: 'right',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: BRUTAL.ink,
    paddingVertical: 11,
    paddingHorizontal: 10,
  },
  itemName: {
    color: BRUTAL.ink,
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
  },
  itemSub: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(8.5),
    fontFamily: FONTS.medium,
    marginTop: 2,
  },
  itemQty: {
    color: BRUTAL.ink,
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
  },
  itemAmt: {
    color: BRUTAL.ink,
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
  },
  totalsBlock: {
    marginTop: hp(0.02),
    gap: 8,
    alignSelf: 'flex-end',
    width: '100%',
    maxWidth: 260,
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: BRUTAL.ink,
    borderWidth: 2,
    borderColor: BRUTAL.ink,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  totalLabel: {
    color: BRUTAL.paper,
    fontSize: fontScale(11),
    fontFamily: FONTS.display,
    letterSpacing: 0.5,
  },
  totalValue: {
    color: BRUTAL.paper,
    fontSize: fontScale(14),
    fontFamily: FONTS.display,
    letterSpacing: 0.5,
  },
  taxNote: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(8),
    fontFamily: FONTS.medium,
    textAlign: 'right',
  },
  freeStamp: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#DCFCE7',
    borderWidth: 2,
    borderColor: '#15803D',
    borderRadius: 2,
    paddingVertical: 10,
  },
  freeStampText: {
    color: '#14532D',
    fontSize: fontScale(10),
    fontFamily: FONTS.bold,
    letterSpacing: 1,
  },
  trailRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: hp(0.022),
    paddingTop: hp(0.018),
    borderTopWidth: 2,
    borderTopColor: 'rgba(23, 18, 12, 0.15)',
  },
  trailRef: {
    flex: 1,
    minWidth: '100%',
  },
  footer: {
    marginTop: hp(0.024),
    backgroundColor: BRUTAL.paperAlt,
    borderWidth: 2,
    borderColor: 'rgba(23, 18, 12, 0.25)',
    borderRadius: 2,
    padding: 10,
    gap: 3,
  },
  footerText: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(8),
    fontFamily: FONTS.medium,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: hp(0.024),
  },
  downloadBtn: {
    flex: 1,
    backgroundColor: BRUTAL.ink,
    borderWidth: 2,
    borderColor: BRUTAL.ink,
    borderRadius: 4,
    minHeight: 48,
  },
  downloadContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  downloadBtnText: {
    color: BRUTAL.paper,
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  doneBtn: {
    flex: 1,
    backgroundColor: BRUTAL.flame,
    borderWidth: 2,
    borderColor: BRUTAL.ink,
    borderRadius: 4,
    minHeight: 48,
  },
  doneContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  doneBtnText: {
    color: BRUTAL.ink,
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  aiAssetCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: BRUTAL.paperAlt,
    borderWidth: 1.5,
    borderColor: BRUTAL.ink,
    borderRadius: 4,
    padding: 8,
    marginTop: 10,
    gap: 10,
  },
  aiAssetThumb: {
    width: 44,
    height: 64,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: BRUTAL.ink,
    backgroundColor: BRUTAL.ink,
  },
  aiAssetInfo: {
    flex: 1,
  },
  aiAssetBadge: {
    alignSelf: 'flex-start',
    backgroundColor: BRUTAL.flame,
    borderWidth: 1,
    borderColor: BRUTAL.ink,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 2,
    marginBottom: 4,
  },
  aiAssetBadgeText: {
    color: BRUTAL.ink,
    fontSize: fontScale(7.5),
    fontFamily: FONTS.bold,
    letterSpacing: 0.8,
  },
  aiAssetTitle: {
    color: BRUTAL.ink,
    fontSize: fontScale(11.5),
    fontFamily: FONTS.bold,
  },
  aiAssetSub: {
    color: BRUTAL.inkMute,
    fontSize: fontScale(8.5),
    fontFamily: FONTS.medium,
    marginTop: 2,
  },
});
