import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../../constants/colors';
import { fontScale, wp, hp, SCREEN_PAD, CARD_SHADOW } from '../../utils/responsive';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  header: {
    marginBottom: hp(0.012),
  },
  clearRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SCREEN_PAD,
    marginBottom: hp(0.012),
  },
  clearHint: {
    color: COLORS.inkMuted,
    fontSize: fontScale(12),
    fontFamily: FONTS.medium,
  },
  clearBtn: {
    backgroundColor: '#Fee2e2',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#Fca5a5',
  },
  clearBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    gap: 4,
  },
  clearBtnText: {
    color: COLORS.error,
    fontSize: fontScale(11),
    fontFamily: FONTS.bold,
  },
  loadingContainer: {
    paddingHorizontal: SCREEN_PAD,
    marginTop: hp(0.02),
  },
  downloadSkeletonCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...CARD_SHADOW,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SCREEN_PAD,
    paddingBottom: hp(0.1),
  },
  emptyIconWrap: {
    width: wp(0.2),
    height: wp(0.2),
    borderRadius: wp(0.1),
    backgroundColor: COLORS.primaryTint || COLORS.orangeTint,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(0.02),
  },
  emptyTitle: {
    color: COLORS.ink,
    fontSize: fontScale(18),
    fontFamily: FONTS.bold,
    textAlign: 'center',
  },
  emptySub: {
    color: COLORS.inkMuted,
    fontSize: fontScale(13),
    fontFamily: FONTS.medium,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: fontScale(19),
  },
  ctaWrap: {
    marginTop: hp(0.03),
  },
  listContent: {
    paddingHorizontal: SCREEN_PAD,
    paddingBottom: hp(0.06),
    gap: hp(0.014),
  },
  card: {
    flexDirection: 'row',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: COLORS.borderStrong,
    padding: wp(0.03),
    alignItems: 'center',
    gap: wp(0.035),
    ...CARD_SHADOW,
  },
  cardLeft: {
    width: wp(0.22),
    aspectRatio: 9 / 16,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: COLORS.surfaceAlt || COLORS.surfaceLight,
    borderWidth: 1,
    borderColor: COLORS.border,
    position: 'relative',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
  },
  cardBody: {
    flex: 1,
    justifyContent: 'center',
  },
  cardTitle: {
    color: COLORS.ink,
    fontSize: fontScale(14),
    fontFamily: FONTS.bold,
  },
  cardDate: {
    color: COLORS.inkMuted,
    fontSize: fontScale(11),
    fontFamily: FONTS.medium,
    marginTop: 2,
  },
  editTag: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.primaryTint || COLORS.orangeTint,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginTop: 6,
  },
  editTagText: {
    color: COLORS.primaryDeep || COLORS.orangeDeep,
    fontSize: fontScale(10),
    fontFamily: FONTS.semibold,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    gap: wp(0.02),
  },
  actionBtnPrimary: {
    backgroundColor: COLORS.primary || COLORS.orange,
    borderRadius: 8,
  },
  actionBtnSecondary: {
    backgroundColor: COLORS.surfaceAlt || '#FFF1F2',
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    borderRadius: 8,
  },
  actionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
  },
  actionTextPrimary: {
    color: COLORS.white,
    fontSize: fontScale(11),
    fontFamily: FONTS.bold,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  actionTextSecondary: {
    color: COLORS.ink,
    fontSize: fontScale(11),
    fontFamily: FONTS.bold,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  deleteIconBtn: {
    backgroundColor: '#Fee2e2',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#Fca5a5',
    marginLeft: 'auto',
  },
  deleteIconContent: {
    padding: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.94)',
    justifyContent: 'space-between',
  },
  fullscreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 14,
    zIndex: 10,
  },
  fullscreenTitle: {
    color: COLORS.white,
    fontSize: fontScale(16),
    fontFamily: FONTS.bold,
    flex: 1,
    marginRight: 12,
  },
  closeBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenContentArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  fullscreenMedia: {
    width: wp(0.96),
    height: hp(0.72),
    borderRadius: 12,
  },
  fullscreenFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  fullscreenActionBtn: {
    flex: 1,
    height: 48,
    backgroundColor: COLORS.primary || COLORS.orange,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: COLORS.ink,
  },
  fullscreenShareBtn: {
    flex: 1,
    height: 48,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: COLORS.ink,
  },
  fullscreenBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    gap: 8,
  },
  fullscreenActionText: {
    color: COLORS.white,
    fontSize: fontScale(13),
    fontFamily: FONTS.bold,
  },
});
