import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../../constants/colors';
import { fontScale, wp, hp, SCREEN_PAD } from '../../utils/responsive';
import { CANVAS_WIDTH, CANVAS_HEIGHT } from './constants';

export const styles = StyleSheet.create({
  payActionBtn: {
    backgroundColor: '#dc2626',
    shadowColor: '#dc2626',
  },
  safeArea: { flex: 1 },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: COLORS.inkMuted,
    fontSize: fontScale(14),
    fontFamily: FONTS.medium,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(0.035),
    paddingVertical: hp(0.012),
  },
  headerLeftGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
  },
  headerBtn: {
    paddingVertical: 6,
    paddingRight: 4,
    paddingLeft: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  templateTitle: {
    flex: 1,
    color: COLORS.ink,
    fontSize: fontScale(15.5),
    fontFamily: FONTS.bold,
    textAlign: 'left',
    marginLeft: 2,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  headerRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  favHeaderBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: COLORS.surfaceAlt,
    borderWidth: 1.2,
    borderColor: COLORS.borderStrong,
    justifyContent: 'center',
    alignItems: 'center',
  },
  favHeaderContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  resetHeaderBtn: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1.2,
    borderColor: COLORS.borderStrong,
    alignSelf: 'center',
    flexShrink: 0,
    flexGrow: 0,
  },
  resetHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
    flex: 0,
    width: 'auto',
    height: 'auto',
  },
  resetHeaderBtnText: {
    color: COLORS.orange,
    fontFamily: FONTS.bold,
    fontSize: fontScale(12),
    includeFontPadding: false,
    textAlignVertical: 'center',
    lineHeight: fontScale(14),
  },
  canvasContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 4,
  },
  canvasSkeletonWrapper: {
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: COLORS.ink,
    elevation: 8,
    shadowColor: COLORS.orangeDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
  },
  canvasSkeletonContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
  },
  skeletonPhotoSlot: {
    width: '65%',
    height: '38%',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(249, 115, 22, 0.3)',
    backgroundColor: 'rgba(249, 115, 22, 0.12)',
    marginTop: '25%',
  },
  skeletonTextLine: {
    width: '70%',
    height: 20,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    marginBottom: '28%',
  },
  skeletonFooterStrip: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '25%',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  editorPanel: {
    backgroundColor: COLORS.surface,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    padding: wp(0.045),
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingBottom: hp(0.02),
  },
  tabHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#FFF1F2',
    borderRadius: 16,
    padding: 4,
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: '#FDA4AF',
  },
  tabItem: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 12,
  },
  tabItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  activeTabItem: {
    backgroundColor: COLORS.orange,
    elevation: 3,
    shadowColor: COLORS.orangeDeep,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
  },
  tabText: {
    color: '#8A7A68',
    fontFamily: FONTS.semibold,
    fontSize: fontScale(12.5),
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  activeTabText: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
  },
  tabContent: {
    minHeight: 110,
    justifyContent: 'center',
  },
  controlsStack: {
    gap: 8,
  },
  photoActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  gallerySelectBtn: {
    flex: 1,
    height: 44,
    backgroundColor: COLORS.orange,
    borderRadius: 14,
    elevation: 3,
    shadowColor: COLORS.orangeDeep,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  gallerySelectContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  gallerySelectText: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
    fontSize: fontScale(13.5),
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  previewActionBtn: {
    height: 44,
    backgroundColor: COLORS.orange,
    borderRadius: 14,
    marginTop: 4,
    elevation: 3,
    shadowColor: COLORS.orangeDeep,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  previewActionContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  previewActionText: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
    fontSize: fontScale(14),
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  textInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  textInputFlex: {
    flex: 1,
    backgroundColor: COLORS.background,
    borderWidth: 1.5,
    borderColor: COLORS.borderStrong,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    color: COLORS.ink,
    fontSize: fontScale(13),
    fontFamily: FONTS.medium,
  },
  deleteIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#fee2e2',
    borderWidth: 1,
    borderColor: '#fca5a5',
  },
  deleteIconContent: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  positioningContainer: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  positionTitle: {
    fontSize: fontScale(10.5),
    fontFamily: FONTS.bold,
    color: COLORS.inkMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  positionPadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  dpadGrid: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  dpadMidRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginVertical: 3,
  },
  dpadBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
  },
  dpadResetBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: COLORS.orangeTint,
    borderWidth: 1,
    borderColor: COLORS.orange,
  },
  dpadContent: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomColumn: {
    alignItems: 'center',
    gap: 4,
  },
  controlSubLabel: {
    fontSize: fontScale(10),
    fontFamily: FONTS.semibold,
    color: COLORS.inkMuted,
  },
  zoomBtn: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
  },
  inputLabel: {
    color: COLORS.inkMuted,
    fontSize: fontScale(10.5),
    fontFamily: FONTS.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  horizontalOptions: {
    gap: 10,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  footersContainer: {
    gap: 8,
  },
  footerSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 2,
    marginBottom: 2,
  },
  footerSectionTitle: {
    color: COLORS.ink,
    fontSize: fontScale(12),
    fontFamily: FONTS.bold,
  },
  footerScrollContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  footerBox: {
    width: hp(0.046),
    height: hp(0.046),
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  footerBoxActive: {
    borderColor: COLORS.orange,
    borderWidth: 2,
    backgroundColor: '#FFF7ED',
    shadowColor: COLORS.orange,
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  footerBoxThumb: {
    width: '100%',
    height: '100%',
  },
  fallbackIconContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  checkBadge: {
    position: 'absolute',
    top: 1,
    right: 1,
    backgroundColor: COLORS.orange,
    borderRadius: 6,
    width: 12,
    height: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  optionChip: {
    backgroundColor: COLORS.surfaceAlt,
    borderWidth: 1.5,
    borderColor: COLORS.borderStrong,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  chipContent: {
    justifyContent: 'center',
  },
  selectedOptionChip: {
    borderColor: COLORS.orange,
    backgroundColor: COLORS.orangeTint,
  },
  optionChipText: {
    color: COLORS.ink,
    fontSize: fontScale(11.5),
    fontFamily: FONTS.semibold,
  },
  selectedOptionChipText: {
    color: COLORS.orange,
  },
});
